source "/home/fortunate/my/Core/core__files.zsh"
source "/home/fortunate/my/Core/core__folders.zsh"
source "/home/fortunate/my/Core/core__mysql.zsh"
source "/home/fortunate/my/Core/core__sed.zsh"
source "/home/fortunate/my/Core/core__shell.zsh"
source "/home/fortunate/my/Core/core__valet.zsh"
source "/home/fortunate/my/Core/core__wordpress.zsh"
